#!/bin/bash

set -e

function update() {
  sudo apt-get update && sudo apt-get upgrade -yy
}

function install_basic() {
  sudo apt-get install -y --no-install-recommends \
    curl \
    git \
    htop \
    make \
    tmux \
    vim \
    autoconf \
    build-essential \
    gdb \
    ctags \
    indent \
    libc6-dev \
    libtool \
    openssh-client \
    rsync
}

function bootstrap() {
  mkdir src && mkdir src/{automata,the-grid,noflo}
}

echo "Installing basic dependencies..."
update
install_basic
echo "Creating working directories..."
bootstrap

