#!/bin/bash

set -e

function update() {
  sudo apt-get update && sudo apt-get upgrade -yy
}

function install_basic() {
  sudo apt-get install -y --no-install-recommends \
    curl \
    git \
    htop \
    make \
    vim \
    autoconf \
    build-essential \
    gdb \
    ctags \
    indent \
    libc6-dev \
    libtool \
    openssh-client \
    rsync \
    irssi
}

function install_libs() {
  sudo apt-get install -y --no-install-recommends \
    libcairo2-dev \
    libgif-dev \
    libopencv-dev \
    libjpeg8-dev \
    libpango1.0-dev \
    libblas-dev \
    libfftw3-dev
}

# Install tmux 2.0
function install_tmux() {
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  sudo add-apt-repository -y ppa:pi-rho/dev
  sudo apt-get update
  sudo apt-get install -y tmux=2.0-1~ppa1~t
}

function bootstrap() {
  echo "- Creating source directories for all projects I work on"
  mkdir src && mkdir src/{automata,the-grid,noflo}
  echo "Fetching dotfiles"
  git clone https://github.com/automata/dotfiles.git ~/src/automata/dotfiles
  echo "Configuring Vim"
  ln -s ~/src/automata/dotfiles/vim/vimrc.symlink ~/.vimrc
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
  echo "Configuring Git"
  ln -s ~/src/automata/dotfiles/git/gitconfig.symlink ~/.gitconfig
  echo "Configuring Tmux"
  ln -s ~/src/automata/dotfiles/tmux/tmux.symlink ~/.tmux.conf
  echo "Configuring Base16 colorscheme on shell"
  git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
  echo "Configuring Base16 (Tomorrow) colorscheme on gnome-terminal"
  git clone https://github.com/chriskempson/base16-gnome-terminal.git ~/.config/base16-gnome-terminal
  source ~/.config/base16-gnome-terminal/base16-tomorrow.dark.sh
  echo "** Open gnome-terminal and choose Base 16 Tomorrow Dark profile, and set as default on preferences **"
}

echo "Installing basic dependencies..."
update
install_basic
install_libs
install_tmux
echo "Bootstraping work environment..."
bootstrap
echo "Type tmux and hack the planet ;-)"
